server:
  port: 8888
spring:
  application:
    name: config-server
  cloud: 
    config:
      server:
        git:
          uri: https://github.com/JulianoNode/jmr-config-server
          # Comandos para Repositorio Privados usuario e senha
          # username: username 
          # password: password
          default-label: main
          search-paths:
          - 'greeting-service*'  