server:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service::
  greeting: "Olá"
  default-value: "Mundo-juliano-perf"